/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Libro;
import modelo.Prestamo;

/**
 *
 * @author JORGE
 */
public class VistaPrestamosCliente extends javax.swing.JFrame {

    ArrayList<Libro> libros;

    /**
     * Creates new form VistaPrestamosCliente
     */
    public VistaPrestamosCliente() {
        initComponents();
        setLocationRelativeTo(this);
        libros = new ArrayList<>();
        agregarListenerTabla();
        Libro libro1 = new Libro("Avatar", "Bill", "0001", "MCqueen", "200", "si", "Fiction");
        Libro libro2 = new Libro("Avatar1", "Bill", "0021", "MCqueen", "230", "si", "aventura");
        Libro libro3 = new Libro("Avatar2", "Bill", "0031", "MCqueen", "240", "si", "drama");
        Libro libro4 = new Libro("Avatar3", "Bill", "0011", "MCqueen", "250", "si", "novela");
        libros.add(libro1);
        libros.add(libro2);
        libros.add(libro3);
        libros.add(libro4);
        llenarTabla();
    }

    
       private void agregarListenerTabla() {
        ListSelectionModel model = tablaLibros.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = tablaLibros.getSelectedRow();
                    if (selectedRow != -1) {
                        // Obtén el valor de la columna "№ Plaza"
                        String placa =  (String) tablaLibros.getValueAt(selectedRow, 2);
                        txtIsbn.setText(placa);
                    }
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        txtIsbn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre", "autor", "isbn", "editorial", "Npaginas", "disponibilidad", "genero"
            }
        ));
        jScrollPane1.setViewportView(tablaLibros);

        jLabel1.setText("ISBN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Prestamo");

        jButton1.setText("Solicitar Prestamo");

        jButton2.setText("regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VistaPrincipalCliente vistaPC = new VistaPrincipalCliente();
        vistaPC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void llenarTabla() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"Nombre", "Autor", "Isbn", "Editorial", "Npag",
            "Disponibilidad", "genero"},
                libros.size());
        tablaLibros.setModel(model);
        TableModel modelP = tablaLibros.getModel();
        for (int i = 0; i < libros.size(); i++) {
            Libro libro = libros.get(i);
            modelP.setValueAt(libro.getNombre(), i, 0);
            modelP.setValueAt(libro.getAutor(), i, 1);
            modelP.setValueAt(libro.getIsbn(), i, 2);
            modelP.setValueAt(libro.getEditorial(), i, 3);
            modelP.setValueAt(libro.getNpaginas(), i, 4);
            modelP.setValueAt(libro.getDisponibilidad(), i, 5);
            modelP.setValueAt(libro.getGenero(), i, 6);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JTextField txtIsbn;
    // End of variables declaration//GEN-END:variables
}
